name: rainforst_biz_project
description: ''
version: 0.0.1
author: satysingh@teksystems.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: rainforstbizproject
  parentArtefactID: satysinghteksystemscomteam
  buildSystem: wheel
  author: null
  createdAt: '2026-01-17 15:10:20'
pipelines:
  pipelines/enrich_accounts:
    name: enrich_accounts
    description: ''
    author: satysingh@teksystems.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2026-01-17 15:10:20'
    datasets:
      inputs:
      - gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=&tag=course_lab_sources/0.0.3&projectSubscriptionProjectId=13587&path=datasets/salesforce-Account
      - gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=&tag=course_lab_sources/0.0.3&projectSubscriptionProjectId=13587&path=datasets/salesforce-Opportunity
      outputs:
      - datasets/enriched_accounts
    subgraphs: []
    dependencies: {}
datasets:
  datasets/enriched_accounts:
    name: enriched_accounts
    description: ''
    author: satysingh@teksystems.com
    createdAt: '2026-01-17 16:27:01'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 36390
        datasetType: Database
        description: ''
        author: satysingh@teksystems.com
        createdAt: '2026-01-17 16:27:01'
templates: {}
jobs:
  jobs/daily_accounts:
    name: daily_accounts
    description: ''
    fabricUID: 36387
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 * * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/enrich_accounts
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2026-01-17 17:03:43'
    author: satysingh@teksystems.com
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2026-01-17 15:10:20'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2026-01-17T15:10:20.487966Z'
  name: plibMaven
  version: 8.16.0
  id: '1921334876'
  createdAt: '2026-01-17T15:10:20.487966Z'
  type: plibMaven
- modifiedAt: '2026-01-17T15:10:20.487966Z'
  name: plibPypi
  version: 2.1.9
  id: '828038146'
  createdAt: '2026-01-17T15:10:20.487966Z'
  type: plibPypi
projectDependencies:
  '13587':
    projectUID: 13587
    projectName: course_lab_sources
    repositoryPath: gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=
    version: course_lab_sources/0.0.3
    isDefault: false
    author: null
    createdAt: '2026-01-17 15:03:43'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.54
    isDefault: true
    author: null
    createdAt: '2026-01-17 15:03:43'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.10
    isDefault: true
    author: null
    createdAt: '2026-01-17 15:03:43'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
projectConfigurations: {}
